hash-format = "sha256"

[[files]]
file = "config/betterdungeons-fabric-1_21.toml"

[[files]]
file = "config/betterstrongholds-fabric-1_21.toml"

[[files]]
file = "config/ribbits-fabric-1_21_1.toml"

[[files]]
file = "config/seasons.json"

[[files]]
file = "config/yosbr/config/cpm.json"

[[files]]
file = "config/yosbr/config/enhanced_bes.properties"

[[files]]
file = "config/yosbr/config/minelp.json"

[[files]]
file = "config/yosbr/options.txt"

[[files]]
file = "config/yosbr/server.properties"

[[files]]
file = "mods/YungsBetterCaves-1.21.1-Fabric-3.1.1.jar"

[[files]]
file = "mods/YungsCaveBiomes-1.21.1-Fabric-3.1.0.jar"

[[files]]
file = "mods/aa4-atlas.pw.toml"
metafile = true

[[files]]
file = "mods/accessories-tc-layer.pw.toml"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
metafile = true

[[files]]
file = "mods/accessorify.pw.toml"
metafile = true

[[files]]
file = "mods/aether-emissivity.pw.toml"
metafile = true

[[files]]
file = "mods/aether-enhanced-extinguishing.pw.toml"
metafile = true

[[files]]
file = "mods/aether-protect-your-moa.pw.toml"
metafile = true

[[files]]
file = "mods/aether-treasure-reforging.pw.toml"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
metafile = true

[[files]]
file = "mods/anshar.pw.toml"
metafile = true

[[files]]
file = "mods/antique-atlas-4.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/athena-mod.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
metafile = true

[[files]]
file = "mods/betterdays.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/blockus.pw.toml"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/colossal-chests.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cpmsvcc.pw.toml"
metafile = true

[[files]]
file = "mods/cryonicconfig.pw.toml"
metafile = true

[[files]]
file = "mods/custom-player-models.pw.toml"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
metafile = true

[[files]]
file = "mods/dawn-of-time.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/dramatic-doors.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
metafile = true

[[files]]
file = "mods/ellies-storage-options.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
metafile = true

[[files]]
file = "mods/explorify.pw.toml"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons-extras.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons-terralith-compat.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
metafile = true

[[files]]
file = "mods/factory-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-beekeeper-hut-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-flowery-mooblooms-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/hopo-better-mineshaft.pw.toml"
metafile = true

[[files]]
file = "mods/hopo-better-ruined-portals.pw.toml"
metafile = true

[[files]]
file = "mods/hopo-better-underwater-ruins.pw.toml"
metafile = true

[[files]]
file = "mods/iceandfire-ce.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersive-snow.pw.toml"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/jupiter.pw.toml"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/modonomicon.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/moremcmeta-emissive.pw.toml"
metafile = true

[[files]]
file = "mods/moremcmeta.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
metafile = true

[[files]]
file = "mods/oceans-delight.pw.toml"
metafile = true

[[files]]
file = "mods/oritech.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
metafile = true

[[files]]
file = "mods/polyfactory.pw.toml"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage-emi-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage-trinkets-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/revelationary.pw.toml"
metafile = true

[[files]]
file = "mods/ribbits.pw.toml"
metafile = true

[[files]]
file = "mods/roguelikedungeons.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/seasons-delight-refab-compat.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/small-ships.pw.toml"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/some-more-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-storage-(unofficial-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-storage-in-motion-(unofficial-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spectrum.pw.toml"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
metafile = true

[[files]]
file = "mods/structory-towers.pw.toml"
metafile = true

[[files]]
file = "mods/structory.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
metafile = true

[[files]]
file = "mods/surveyor.pw.toml"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
metafile = true

[[files]]
file = "mods/templates-2.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/terralith-biome-saplings.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/timeoutout.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia-blockus-addon.pw.toml"
metafile = true

[[files]]
file = "mods/unicopia.pw.toml"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
metafile = true

[[files]]
file = "mods/uranus.pw.toml"
metafile = true

[[files]]
file = "mods/vanillabackport.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
metafile = true

[[files]]
file = "mods/yungs-menu-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resources/datapack/required/VanillaTweaks_c413640_MC1.21-1.21.7.zip"

[[files]]
file = "resources/datapack/required/double shulker shells v1.3.13 (MC 1.21-1.21.7).zip"

[[files]]
file = "resources/datapack/required/wandering trader announcements v1.0.6 (MC 1.21-1.21.7).zip"

[[files]]
file = "resources/resourcepack/optional/VanillaTweaks_r163854_MC1.21.x.zip"

[[files]]
file = "resources/resourcepack/optional/better-leaves.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/antique-atlas-4-compat.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/sparkles-addon-alpha-islands.pw.toml"
metafile = true

[[files]]
file = "resources/resourcepack/required/sparkles.pw.toml"
metafile = true
