name = "Skycraft 2"
author = "Nyx"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62a9439b6b72660fd1a0758acc4e1540e296ecf8cf114f5d26ddc516ae435113"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
