name = "Skycraft 2"
author = "Nyx"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe4684d85d6d65046105ff4e2d1f651a7d7ab3834d5c7474b7596a61b516e1dc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
no-internal-hashes = true
