name = "Skycraft 2"
author = "Nyx"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8c6925cc75a95ed985d58fb363daae8fe3cc7f87bd8086ec9c47ef9bfe0d188"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
