name = "Skycraft 2"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f17b5aa81c5484aae0a4b332a499a16e41149025657908cdd94d1e77ec6bdfbd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
