name = "Skycraft 2"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27ec1dd3e1795fedc491b791f5e088ec6c49e178ad58cd92bfb1620b07f65fd6"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
