name = "Skycraft 2"
author = "Nyx"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4dced15e788842113cac2e4855b12b6d00f4ab9a7b746954fb99f172b88d4222"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
